import "~/styles/globals.css";
import ReduxProvider from "~/store/reduxProvider";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "../components/navbar";
import TopBar from "./pages/shop/topBar";
import Footer from "../components/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {" "}
        <TopBar time={{ hours: 0, minutes: 7, seconds: 27 }}></TopBar>
        <Navbar></Navbar>
        <ReduxProvider>{children}</ReduxProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
